"""subsrcibers change

Revision ID: 382291e47bf6
Revises: 23e65383d014
Create Date: 2018-09-16 17:07:29.656175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '382291e47bf6'
down_revision = '23e65383d014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
